FROM dotenc-e2e

# Install a Node runtime for the CLI-under-test.
RUN apt-get update && \
	apt-get install -y nodejs && \
	rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["bash", "/app/cli/e2e/run-coverage.sh"]
